CREATE TABLE IF NOT EXISTS `question` (
    `question_id` VARCHAR(255) NOT NULL COMMENT '题目ID',
    `question_content` LONGTEXT NOT NULL COMMENT '题干',
    `question_image_base64` LONGTEXT DEFAULT NULL COMMENT '题目图片Base64',
    `option_1` TEXT DEFAULT NULL COMMENT '备选答案1',
    `option_2` TEXT DEFAULT NULL COMMENT '备选答案2',
    `option_3` TEXT DEFAULT NULL COMMENT '备选答案3',
    `option_4` TEXT DEFAULT NULL COMMENT '备选答案4',
    `option_5` TEXT DEFAULT NULL COMMENT '备选答案5',
    `option_6` TEXT DEFAULT NULL COMMENT '备选答案6',
    `option_7` TEXT DEFAULT NULL COMMENT '备选答案7',
    `option_8` TEXT DEFAULT NULL COMMENT '备选答案8',
    `answer_content` JSON DEFAULT NULL COMMENT '正确答案JSON数组，例如 ["A","B"]',
    `answer_source` VARCHAR(255) DEFAULT NULL COMMENT '答案来源',
    `question_year` VARCHAR(255) DEFAULT NULL COMMENT '题目年份',
    `question_source` VARCHAR(255) DEFAULT NULL COMMENT '题目来源',
    `correct_rate` VARCHAR(255) DEFAULT NULL COMMENT '正确率，保留原始文本',
    `question_status` TINYINT NOT NULL DEFAULT 1 COMMENT '状态：0-禁用，1-启用',
    `created_time` DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP COMMENT '创建时间',
    `updated_time` DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP COMMENT '更新时间',
    `EXT_FIELD_1` VARCHAR(255) DEFAULT NULL COMMENT '扩展字段1',
    `EXT_FIELD_2` VARCHAR(255) DEFAULT NULL COMMENT '扩展字段2',
    `EXT_FIELD_3` VARCHAR(255) DEFAULT NULL COMMENT '扩展字段3',
    `EXT_FIELD_4` VARCHAR(255) DEFAULT NULL COMMENT '扩展字段4',
    `EXT_FIELD_5` VARCHAR(255) DEFAULT NULL COMMENT '扩展字段5',
    PRIMARY KEY (`question_id`),
    KEY `idx_question_year_source` (`question_year`, `question_source`),
    KEY `idx_question_status_created` (`question_status`, `created_time`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci COMMENT='刷题题目表';

CREATE TABLE IF NOT EXISTS `answer_record` (
    `answer_record_id` BIGINT UNSIGNED NOT NULL AUTO_INCREMENT COMMENT '作答记录ID',
    `question_id` VARCHAR(255) NOT NULL COMMENT '题目ID',
    `user_id` BIGINT UNSIGNED DEFAULT NULL COMMENT '用户ID，未接入用户体系时可为空',
    `session_id` VARCHAR(255) DEFAULT NULL COMMENT '练习会话ID',
    `selected_answer` VARCHAR(255) NOT NULL COMMENT '用户选择答案，支持单选或多选，例如 A、AB',
    `correct_answer` VARCHAR(255) NOT NULL COMMENT '作答时的正确答案快照',
    `is_correct` TINYINT NOT NULL COMMENT '是否答对：0-错误，1-正确',
    `start_time` DATETIME NOT NULL COMMENT '开始作答时间',
    `end_time` DATETIME NOT NULL COMMENT '结束作答时间',
    `created_time` DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP COMMENT '创建时间',
    `updated_time` DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP COMMENT '更新时间',
    `EXT_FIELD_1` VARCHAR(255) DEFAULT NULL COMMENT '扩展字段1',
    `EXT_FIELD_2` VARCHAR(255) DEFAULT NULL COMMENT '扩展字段2',
    `EXT_FIELD_3` VARCHAR(255) DEFAULT NULL COMMENT '扩展字段3',
    `EXT_FIELD_4` VARCHAR(255) DEFAULT NULL COMMENT '扩展字段4',
    `EXT_FIELD_5` VARCHAR(255) DEFAULT NULL COMMENT '扩展字段5',
    PRIMARY KEY (`answer_record_id`),
    KEY `idx_answer_record_question_time` (`question_id`, `end_time`),
    KEY `idx_answer_record_user_time` (`user_id`, `end_time`),
    KEY `idx_answer_record_session_time` (`session_id`, `end_time`),
    KEY `idx_answer_record_correct` (`is_correct`, `end_time`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci COMMENT='刷题作答记录表';

CREATE TABLE IF NOT EXISTS `SYS_USER` (
    `USER_ID` BIGINT UNSIGNED NOT NULL AUTO_INCREMENT COMMENT '用户ID',
    `USERNAME` VARCHAR(64) NOT NULL COMMENT '登录用户名',
    `PASSWORD_HASH` VARCHAR(200) NOT NULL COMMENT '密码哈希',
    `NICK_NAME` VARCHAR(100) NOT NULL COMMENT '昵称',
    `USER_STATUS` TINYINT NOT NULL DEFAULT 1 COMMENT '状态：1正常 2禁用 3逻辑删除',
    `IS_DELETE` TINYINT NOT NULL DEFAULT 1 COMMENT '是否允许删除：0不允许 1允许',
    `IS_ALLOW_ROLE_CHANGE` TINYINT NOT NULL DEFAULT 1 COMMENT '是否允许修改角色：0不允许 1允许',
    `CREATE_TIME` DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP COMMENT '创建时间',
    `UPDATE_TIME` DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP COMMENT '更新时间',
    PRIMARY KEY (`USER_ID`),
    UNIQUE KEY `uk_sys_user_username` (`USERNAME`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci COMMENT='系统用户表';

CREATE TABLE IF NOT EXISTS `SYS_ROLE` (
    `ROLE_ID` BIGINT UNSIGNED NOT NULL AUTO_INCREMENT COMMENT '角色ID',
    `ROLE_CODE` VARCHAR(64) NOT NULL COMMENT '角色编码',
    `ROLE_NAME` VARCHAR(100) NOT NULL COMMENT '角色名称',
    `ROLE_STATUS` TINYINT NOT NULL DEFAULT 1 COMMENT '状态：1正常 2禁用 3逻辑删除',
    `IS_DELETE` TINYINT NOT NULL DEFAULT 1 COMMENT '是否允许删除：0不允许 1允许',
    `CREATE_TIME` DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP COMMENT '创建时间',
    `UPDATE_TIME` DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP COMMENT '更新时间',
    PRIMARY KEY (`ROLE_ID`),
    UNIQUE KEY `uk_sys_role_code` (`ROLE_CODE`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci COMMENT='系统角色表';

CREATE TABLE IF NOT EXISTS `SYS_API` (
    `API_ID` BIGINT UNSIGNED NOT NULL AUTO_INCREMENT COMMENT '接口权限ID',
    `API_CODE` VARCHAR(100) NOT NULL COMMENT '接口权限编码',
    `API_NAME` VARCHAR(200) NOT NULL COMMENT '接口权限名称',
    `API_PATH` VARCHAR(255) DEFAULT NULL COMMENT '接口路径',
    `HTTP_METHOD` VARCHAR(20) DEFAULT NULL COMMENT 'HTTP方法',
    `STATUS` TINYINT NOT NULL DEFAULT 1 COMMENT '状态：1启用 2禁用',
    `CREATE_TIME` DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP COMMENT '创建时间',
    `UPDATE_TIME` DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP COMMENT '更新时间',
    PRIMARY KEY (`API_ID`),
    UNIQUE KEY `uk_sys_api_code` (`API_CODE`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci COMMENT='系统接口权限表';

CREATE TABLE IF NOT EXISTS `SYS_USER_ROLE` (
    `ID` BIGINT UNSIGNED NOT NULL AUTO_INCREMENT COMMENT '主键ID',
    `USER_ID` BIGINT UNSIGNED NOT NULL COMMENT '用户ID',
    `ROLE_ID` BIGINT UNSIGNED NOT NULL COMMENT '角色ID',
    `CREATE_TIME` DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP COMMENT '创建时间',
    PRIMARY KEY (`ID`),
    UNIQUE KEY `uk_sys_user_role_user_id` (`USER_ID`),
    KEY `idx_sys_user_role_role_id` (`ROLE_ID`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci COMMENT='用户角色关联表';

CREATE TABLE IF NOT EXISTS `SYS_ROLE_API_PERMISSION` (
    `ID` BIGINT UNSIGNED NOT NULL AUTO_INCREMENT COMMENT '主键ID',
    `ROLE_ID` BIGINT UNSIGNED NOT NULL COMMENT '角色ID',
    `API_ID` BIGINT UNSIGNED NOT NULL COMMENT '接口权限ID',
    `CREATE_TIME` DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP COMMENT '创建时间',
    PRIMARY KEY (`ID`),
    UNIQUE KEY `uk_sys_role_api_permission` (`ROLE_ID`, `API_ID`),
    KEY `idx_sys_role_api_permission_api_id` (`API_ID`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci COMMENT='角色接口权限关联表';

CREATE TABLE IF NOT EXISTS `SYS_USER_TOKEN_VERSION` (
    `USER_ID` BIGINT UNSIGNED NOT NULL COMMENT '用户ID',
    `TOKEN_VERSION` INT NOT NULL DEFAULT 1 COMMENT '令牌版本号',
    `UPDATE_TIME` DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP COMMENT '更新时间',
    PRIMARY KEY (`USER_ID`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci COMMENT='用户令牌版本表';
