DROP TABLE IF EXISTS `QUESTION`;
CREATE TABLE IF NOT EXISTS `QUESTION` (
    `QUESTION_ID` VARCHAR(255) NOT NULL COMMENT '题目ID',
    `USER_ID` BIGINT UNSIGNED NOT NULL COMMENT '题目归属用户ID',
    `QUESTION_TYPE` TINYINT NOT NULL DEFAULT 1 COMMENT '题目类型：1-单选，2-多选',
    `QUESTION_CATEGORY` VARCHAR(64) DEFAULT NULL COMMENT '题目科目分类，例如言语理解、判断推理',
    `QUESTION_CONTENT` LONGTEXT NOT NULL COMMENT '题干',
    `QUESTION_IMAGE_BASE64` LONGTEXT DEFAULT NULL COMMENT '题目图片Base64',
    `OPTION_1` TEXT DEFAULT NULL COMMENT '备选答案1',
    `OPTION_2` TEXT DEFAULT NULL COMMENT '备选答案2',
    `OPTION_3` TEXT DEFAULT NULL COMMENT '备选答案3',
    `OPTION_4` TEXT DEFAULT NULL COMMENT '备选答案4',
    `OPTION_5` TEXT DEFAULT NULL COMMENT '备选答案5',
    `OPTION_6` TEXT DEFAULT NULL COMMENT '备选答案6',
    `OPTION_7` TEXT DEFAULT NULL COMMENT '备选答案7',
    `OPTION_8` TEXT DEFAULT NULL COMMENT '备选答案8',
    `ANSWER_CONTENT` JSON DEFAULT NULL COMMENT '正确答案JSON数组，例如 ["A","B"]',
    `ANSWER_SOURCE` VARCHAR(255) DEFAULT NULL COMMENT '答案来源',
    `QUESTION_YEAR` VARCHAR(255) DEFAULT NULL COMMENT '题目年份',
    `QUESTION_SOURCE` VARCHAR(255) DEFAULT NULL COMMENT '题目来源',
    `QUESTION_JOIN_DATE` DATE DEFAULT NULL COMMENT '题目加入日期',
    `CORRECT_RATE` VARCHAR(255) DEFAULT NULL COMMENT '正确率，保留原始文本',
    `QUESTION_STATUS` TINYINT NOT NULL DEFAULT 1 COMMENT '状态：0-禁用，1-启用',
    `CREATED_TIME` DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP COMMENT '创建时间',
    `UPDATED_TIME` DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP COMMENT '更新时间',
    `EXT_FIELD_1` VARCHAR(255) DEFAULT NULL COMMENT '扩展字段1',
    `EXT_FIELD_2` VARCHAR(255) DEFAULT NULL COMMENT '扩展字段2',
    `EXT_FIELD_3` VARCHAR(255) DEFAULT NULL COMMENT '扩展字段3',
    `EXT_FIELD_4` VARCHAR(255) DEFAULT NULL COMMENT '扩展字段4',
    `EXT_FIELD_5` VARCHAR(255) DEFAULT NULL COMMENT '扩展字段5',
    PRIMARY KEY (`USER_ID`, `QUESTION_ID`),
    KEY `IDX_QUESTION_CATEGORY` (`USER_ID`, `QUESTION_CATEGORY`),
    KEY `IDX_QUESTION_YEAR_SOURCE` (`USER_ID`, `QUESTION_YEAR`, `QUESTION_SOURCE`),
    KEY `IDX_QUESTION_JOIN_DATE` (`USER_ID`, `QUESTION_JOIN_DATE`),
    KEY `IDX_QUESTION_STATUS_CREATED` (`USER_ID`, `QUESTION_STATUS`, `CREATED_TIME`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci COMMENT='刷题题目表';

DROP TABLE IF EXISTS `QUESTION_ANALYSIS`;
CREATE TABLE IF NOT EXISTS `QUESTION_ANALYSIS` (
    `QUESTION_ID` VARCHAR(255) NOT NULL COMMENT '题目ID',
    `USER_ID` BIGINT UNSIGNED NOT NULL COMMENT '解析归属用户ID',
    `ANALYSIS_CONTENT` LONGTEXT DEFAULT NULL COMMENT '题目解析文本',
    `ANALYSIS_IMAGE_BASE64` LONGTEXT DEFAULT NULL COMMENT '题目解析图片Base64',
    `CREATED_TIME` DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP COMMENT '创建时间',
    `UPDATED_TIME` DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP COMMENT '更新时间',
    `EXT_FIELD_1` VARCHAR(255) DEFAULT NULL COMMENT '扩展字段1',
    `EXT_FIELD_2` VARCHAR(255) DEFAULT NULL COMMENT '扩展字段2',
    `EXT_FIELD_3` VARCHAR(255) DEFAULT NULL COMMENT '扩展字段3',
    `EXT_FIELD_4` VARCHAR(255) DEFAULT NULL COMMENT '扩展字段4',
    `EXT_FIELD_5` VARCHAR(255) DEFAULT NULL COMMENT '扩展字段5',
    PRIMARY KEY (`USER_ID`, `QUESTION_ID`),
    KEY `IDX_QUESTION_ANALYSIS_UPDATED` (`USER_ID`, `UPDATED_TIME`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci COMMENT='刷题题目解析表';

DROP TABLE IF EXISTS `ANSWER_RECORD`;
CREATE TABLE IF NOT EXISTS `ANSWER_RECORD` (
    `ANSWER_RECORD_ID` BIGINT UNSIGNED NOT NULL AUTO_INCREMENT COMMENT '作答记录ID',
    `QUESTION_ID` VARCHAR(255) NOT NULL COMMENT '题目ID',
    `USER_ID` BIGINT UNSIGNED NOT NULL COMMENT '作答用户ID',
    `SESSION_ID` VARCHAR(255) DEFAULT NULL COMMENT '练习会话ID',
    `SELECTED_ANSWER` JSON NOT NULL COMMENT '用户选择答案JSON数组，例如 ["A","B"]',
    `CORRECT_ANSWER` JSON NOT NULL COMMENT '作答时的正确答案快照JSON数组，例如 ["A","B"]',
    `IS_CORRECT` TINYINT NOT NULL COMMENT '是否答对：0-错误，1-正确',
    `START_TIME` DATETIME NOT NULL COMMENT '开始作答时间',
    `END_TIME` DATETIME NOT NULL COMMENT '结束作答时间',
    `CREATED_TIME` DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP COMMENT '创建时间',
    `UPDATED_TIME` DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP COMMENT '更新时间',
    `EXT_FIELD_1` VARCHAR(255) DEFAULT NULL COMMENT '扩展字段1',
    `EXT_FIELD_2` VARCHAR(255) DEFAULT NULL COMMENT '扩展字段2',
    `EXT_FIELD_3` VARCHAR(255) DEFAULT NULL COMMENT '扩展字段3',
    `EXT_FIELD_4` VARCHAR(255) DEFAULT NULL COMMENT '扩展字段4',
    `EXT_FIELD_5` VARCHAR(255) DEFAULT NULL COMMENT '扩展字段5',
    PRIMARY KEY (`ANSWER_RECORD_ID`),
    KEY `IDX_ANSWER_RECORD_QUESTION_TIME` (`USER_ID`, `QUESTION_ID`, `END_TIME`),
    KEY `IDX_ANSWER_RECORD_USER_TIME` (`USER_ID`, `END_TIME`),
    KEY `IDX_ANSWER_RECORD_SESSION_TIME` (`SESSION_ID`, `END_TIME`),
    KEY `IDX_ANSWER_RECORD_CORRECT` (`IS_CORRECT`, `END_TIME`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci COMMENT='刷题作答记录表';

DROP TABLE IF EXISTS `SYS_USER`;
CREATE TABLE IF NOT EXISTS `SYS_USER` (
    `USER_ID` BIGINT UNSIGNED NOT NULL AUTO_INCREMENT COMMENT '用户ID',
    `USERNAME` VARCHAR(64) NOT NULL COMMENT '登录用户名',
    `PASSWORD_HASH` VARCHAR(200) NOT NULL COMMENT '密码哈希',
    `NICK_NAME` VARCHAR(100) NOT NULL COMMENT '昵称',
    `USER_STATUS` TINYINT NOT NULL DEFAULT 1 COMMENT '状态：1正常 2禁用 3逻辑删除',
    `IS_DELETE` TINYINT NOT NULL DEFAULT 1 COMMENT '是否允许删除：0不允许 1允许',
    `IS_ALLOW_ROLE_CHANGE` TINYINT NOT NULL DEFAULT 1 COMMENT '是否允许修改角色：0不允许 1允许',
    `CREATE_TIME` DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP COMMENT '创建时间',
    `UPDATE_TIME` DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP COMMENT '更新时间',
    PRIMARY KEY (`USER_ID`),
    UNIQUE KEY `UK_SYS_USER_USERNAME` (`USERNAME`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci COMMENT='系统用户表';

DROP TABLE IF EXISTS `SYS_ROLE`;
CREATE TABLE IF NOT EXISTS `SYS_ROLE` (
    `ROLE_ID` BIGINT UNSIGNED NOT NULL AUTO_INCREMENT COMMENT '角色ID',
    `ROLE_CODE` VARCHAR(64) NOT NULL COMMENT '角色编码',
    `ROLE_NAME` VARCHAR(100) NOT NULL COMMENT '角色名称',
    `ROLE_STATUS` TINYINT NOT NULL DEFAULT 1 COMMENT '状态：1正常 2禁用 3逻辑删除',
    `IS_DELETE` TINYINT NOT NULL DEFAULT 1 COMMENT '是否允许删除：0不允许 1允许',
    `CREATE_TIME` DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP COMMENT '创建时间',
    `UPDATE_TIME` DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP COMMENT '更新时间',
    PRIMARY KEY (`ROLE_ID`),
    UNIQUE KEY `UK_SYS_ROLE_CODE` (`ROLE_CODE`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci COMMENT='系统角色表';

DROP TABLE IF EXISTS `SYS_API`;
CREATE TABLE IF NOT EXISTS `SYS_API` (
    `API_ID` BIGINT UNSIGNED NOT NULL AUTO_INCREMENT COMMENT '接口权限ID',
    `API_CODE` VARCHAR(100) NOT NULL COMMENT '接口权限编码',
    `API_NAME` VARCHAR(200) NOT NULL COMMENT '接口权限名称',
    `API_PATH` VARCHAR(255) DEFAULT NULL COMMENT '接口路径',
    `HTTP_METHOD` VARCHAR(20) DEFAULT NULL COMMENT 'HTTP方法',
    `STATUS` TINYINT NOT NULL DEFAULT 1 COMMENT '状态：1启用 2禁用',
    `CREATE_TIME` DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP COMMENT '创建时间',
    `UPDATE_TIME` DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP COMMENT '更新时间',
    PRIMARY KEY (`API_ID`),
    UNIQUE KEY `UK_SYS_API_CODE` (`API_CODE`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci COMMENT='系统接口权限表';

DROP TABLE IF EXISTS `SYS_USER_ROLE`;
CREATE TABLE IF NOT EXISTS `SYS_USER_ROLE` (
    `ID` BIGINT UNSIGNED NOT NULL AUTO_INCREMENT COMMENT '主键ID',
    `USER_ID` BIGINT UNSIGNED NOT NULL COMMENT '用户ID',
    `ROLE_ID` BIGINT UNSIGNED NOT NULL COMMENT '角色ID',
    `CREATE_TIME` DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP COMMENT '创建时间',
    PRIMARY KEY (`ID`),
    UNIQUE KEY `UK_SYS_USER_ROLE_USER_ID` (`USER_ID`),
    KEY `IDX_SYS_USER_ROLE_ROLE_ID` (`ROLE_ID`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci COMMENT='用户角色关联表';

DROP TABLE IF EXISTS `SYS_ROLE_API_PERMISSION`;
CREATE TABLE IF NOT EXISTS `SYS_ROLE_API_PERMISSION` (
    `ID` BIGINT UNSIGNED NOT NULL AUTO_INCREMENT COMMENT '主键ID',
    `ROLE_ID` BIGINT UNSIGNED NOT NULL COMMENT '角色ID',
    `API_ID` BIGINT UNSIGNED NOT NULL COMMENT '接口权限ID',
    `CREATE_TIME` DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP COMMENT '创建时间',
    PRIMARY KEY (`ID`),
    UNIQUE KEY `UK_SYS_ROLE_API_PERMISSION` (`ROLE_ID`, `API_ID`),
    KEY `IDX_SYS_ROLE_API_PERMISSION_API_ID` (`API_ID`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci COMMENT='角色接口权限关联表';

DROP TABLE IF EXISTS `SYS_USER_TOKEN_VERSION`;
CREATE TABLE IF NOT EXISTS `SYS_USER_TOKEN_VERSION` (
    `USER_ID` BIGINT UNSIGNED NOT NULL COMMENT '用户ID',
    `TOKEN_VERSION` INT NOT NULL DEFAULT 1 COMMENT '令牌版本号',
    `UPDATE_TIME` DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP COMMENT '更新时间',
    PRIMARY KEY (`USER_ID`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci COMMENT='用户令牌版本表';

DROP TABLE IF EXISTS `SYS_USER_API_KEY`;
CREATE TABLE IF NOT EXISTS `SYS_USER_API_KEY` (
    `API_KEY_ID` BIGINT UNSIGNED NOT NULL AUTO_INCREMENT COMMENT 'API Key ID',
    `USER_ID` BIGINT UNSIGNED NOT NULL COMMENT '用户ID',
    `API_KEY_NAME` VARCHAR(100) NOT NULL COMMENT 'API Key名称',
    `API_KEY_PREFIX` VARCHAR(32) NOT NULL COMMENT 'API Key前缀，用于快速定位',
    `API_KEY_HASH` VARCHAR(128) NOT NULL COMMENT 'API Key HMAC-SHA256哈希值',
    `API_KEY_STATUS` TINYINT NOT NULL DEFAULT 1 COMMENT '状态：1启用 2禁用',
    `EXPIRE_TIME` DATETIME DEFAULT NULL COMMENT '过期时间，空表示不过期',
    `LAST_USED_TIME` DATETIME DEFAULT NULL COMMENT '最后使用时间',
    `CREATE_TIME` DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP COMMENT '创建时间',
    `UPDATE_TIME` DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP COMMENT '更新时间',
    PRIMARY KEY (`API_KEY_ID`),
    KEY `IDX_SYS_USER_API_KEY_USER_ID` (`USER_ID`),
    KEY `IDX_SYS_USER_API_KEY_PREFIX` (`API_KEY_PREFIX`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci COMMENT='用户API Key表';
